# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded chitin 0.1 "set env(MEMBRANEDIR) [list $dir]; [list source [file join $dir chitin-gui.tcl]]"

#to generate the menu, but returns an error
#to give the installatino directory to vmd:
#export TCLLIBPATH="/path $TCLLIBPATH"
vmd_install_extension chitin chitin_tk    "Modeling/Chitin Builder"

